import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAppDispatch } from '../../../store/hooks'
import { resetSetup } from '../../../store/slices/sessionSetupSlice'
import { useSessionReportQuery } from '../hooks/useInterviewQueries'
import styles from '../styles/interview.module.css'

interface SessionReportCardProps {
  sessionId: string
}

export const SessionReportCard: React.FC<SessionReportCardProps> = ({ sessionId }) => {
  const navigate = useNavigate()
  const dispatch = useAppDispatch()
  const [copyFeedback, setCopyFeedback] = useState(false)

  const { data: report, isLoading, isError, error } = useSessionReportQuery(sessionId)

  const handleCopySummary = async () => {
    if (!report) return
    const text = `Candidate Mock Interview Report
Session ID: ${sessionId}
Confidence Score: ${report.confidenceScore} / 10
Answer Quality Score: ${report.answerQualityScore} / 10

Key Strengths:
${report.strengths.map((s) => `• ${s}`).join('\n')}

Areas for Improvement:
${report.weaknesses.map((w) => `• ${w}`).join('\n')}

Actionable Advice:
${report.advice}
`
    try {
      await navigator.clipboard.writeText(text)
      setCopyFeedback(true)
      setTimeout(() => setCopyFeedback(false), 2500)
    } catch {
      // Fallback
    }
  }

  const handleStartNewSession = () => {
    dispatch(resetSetup())
    navigate('/prep')
  }

  if (isLoading) {
    return (
      <div className={styles.card}>
        <div className={styles.progressItem}>
          <div className={styles.spinner} />
          <div className={styles.progressTextGroup}>
            <p className={styles.progressTitle}>Loading interview performance evaluation...</p>
            <p className={styles.progressDetail}>Synthesizing confidence metrics and structured advice.</p>
          </div>
        </div>
      </div>
    )
  }

  if (isError || !report) {
    return (
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <h2 className={styles.cardTitle}>Report Pending or Not Found</h2>
          <p className={styles.cardDescription}>
            The report for session <code style={{ color: '#2563eb' }}>{sessionId}</code> has not been generated yet or the interview is still in progress.
          </p>
        </div>
        <div className={styles.alertError}>
          <span>⚠️</span>
          <span>{error instanceof Error ? error.message : 'No report data found.'}</span>
        </div>
        <div className={styles.buttonRow}>
          <button
            type="button"
            className={styles.btnSecondary}
            onClick={() => navigate(`/sessions/${sessionId}/interview`)}
          >
            ← Back to Interview Room
          </button>
          <button
            type="button"
            className={styles.btnPrimary}
            onClick={handleStartNewSession}
          >
            Start New Setup
          </button>
        </div>
      </div>
    )
  }

  const confidencePct = Math.min(100, Math.max(0, (report.confidenceScore / 10) * 100))
  const qualityPct = Math.min(100, Math.max(0, (report.answerQualityScore / 10) * 100))

  return (
    <div className={styles.card}>
      <div className={styles.cardHeader}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
          <h2 className={styles.cardTitle}>
            <span>📊</span>
            <span>Performance Evaluation Report</span>
          </h2>
          <span className={styles.badge}>Completed</span>
        </div>
        <p className={styles.cardDescription}>
          Comprehensive candidate assessment generated by the AI interview agent based on your transcribed answers and grounding JD.
        </p>
      </div>

      {/* Score Grid */}
      <div className={styles.reportGrid}>
        <div className={styles.scoreCard}>
          <span className={styles.scoreHeader}>Confidence Score</span>
          <div className={styles.scoreRow}>
            <span className={styles.scoreNumber}>{report.confidenceScore}</span>
            <span className={styles.scoreTotal}>/ 10</span>
          </div>
          <div className={styles.scoreBarTrack}>
            <div
              className={styles.scoreBarFill}
              style={{ width: `${confidencePct}%` }}
            />
          </div>
        </div>

        <div className={styles.scoreCard}>
          <span className={styles.scoreHeader}>Answer Quality Score</span>
          <div className={styles.scoreRow}>
            <span className={styles.scoreNumber}>{report.answerQualityScore}</span>
            <span className={styles.scoreTotal}>/ 10</span>
          </div>
          <div className={styles.scoreBarTrack}>
            <div
              className={styles.scoreBarFill}
              style={{ width: `${qualityPct}%` }}
            />
          </div>
        </div>
      </div>

      {/* Strengths */}
      <div className={styles.formGroup}>
        <h3 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0', color: '#0f172a' }}>
          Key Strengths
        </h3>
        {report.strengths.length > 0 ? (
          <ul className={styles.reportList}>
            {report.strengths.map((str, idx) => (
              <li key={idx} className={styles.reportListItem}>
                <span className={styles.bulletIconSuccess}>✓</span>
                <span>{str}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p style={{ fontSize: '13px', color: '#64748b' }}>No strengths noted.</p>
        )}
      </div>

      {/* Weaknesses / Areas for Improvement */}
      <div className={styles.formGroup}>
        <h3 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0', color: '#0f172a' }}>
          Areas for Improvement
        </h3>
        {report.weaknesses.length > 0 ? (
          <ul className={styles.reportList}>
            {report.weaknesses.map((w, idx) => (
              <li key={idx} className={styles.reportListItem}>
                <span className={styles.bulletIconWarning}>!</span>
                <span>{w}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p style={{ fontSize: '13px', color: '#64748b' }}>No major weaknesses identified.</p>
        )}
      </div>

      {/* Actionable Advice */}
      <div className={styles.formGroup}>
        <h3 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0', color: '#0f172a' }}>
          Structured Preparation Advice
        </h3>
        <div className={styles.adviceBox}>{report.advice}</div>
      </div>

      {/* Actions */}
      <div className={styles.buttonRow}>
        <button
          type="button"
          className={styles.btnSecondary}
          onClick={handleCopySummary}
        >
          {copyFeedback ? '✓ Copied to Clipboard!' : '📋 Copy Report Summary'}
        </button>
        <button
          type="button"
          className={styles.btnSecondary}
          onClick={() => window.print()}
        >
          🖨️ Print / Save PDF
        </button>
        <button
          type="button"
          className={styles.btnPrimary}
          onClick={handleStartNewSession}
        >
          <span>Start Another Practice Session</span>
          <span>→</span>
        </button>
      </div>
    </div>
  )
}
